[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
traccia = "2.2.5"
gtk = { path = "../gtk" }
clap = { version = "4.5.42", features = ["derive"] }
tokio = { version = "1.47.1", features = ["full"] }
which = "8.0.0"
common = { path = "../common" }
phf = { version = "0.12.1", features = ["macros"] }

[[bin]]
name = "skadi"
path = "src/main.rs"