[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk4.workspace = true
gtk4-layer-shell.workspace = true
common.workspace = true
traccia.workspace = true
axum = "0.8.6"
tower-http = { version = "0.6.6", features = ["cors", "fs"] }
tokio.workspace = true
serde.workspace = true
webkit6.workspace = true
serde_json.workspace = true 
