[package]
name = "wwwatch"
version = "0.1.0"
edition = "2024"

[dependencies]
swayipc = "4.0.0"
serde.workspace = true
serde_json.workspace = true
clap.workspace = true
tokio.workspace = true
sysinfo = "0.37.2"
zbus = { version = "5.12.0", features = ["tokio"] }
image = "0.25.9"
common.workspace = true
